import { useState } from "react";
import { AlertTriangle, ArrowLeft, Bot, Check, Cpu, Lightbulb, Power, RotateCcw, Settings, Volume2, Wrench } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageHeader } from "./fixmate-ui";

const problems = [
  { name: "LED Not Working", icon: Lightbulb, symptom: "Light stays off or flickers" }, { name: "Motor Not Working", icon: Settings, symptom: "No rotation or stalls" }, { name: "Arduino Problem", icon: Cpu, symptom: "Board resets or will not upload" }, { name: "Buzzer Not Working", icon: Volume2, symptom: "No tone or weak output" }, { name: "No Power / No Output", icon: Power, symptom: "Entire circuit is inactive" }, { name: "Other Circuit Problem", icon: Wrench, symptom: "A different or unclear fault" },
];
const questions = ["Is the circuit receiving the expected supply voltage?", "Are all component polarities and pin connections correct?", "Do the wires and solder joints look secure?", "Does replacing the suspected component restore output?"];

export function DiagnoseFlow() {
  const [selected, setSelected] = useState<number | null>(null); const [step, setStep] = useState(0); const [done, setDone] = useState(false);
  const choose = (answer: boolean) => { if (step >= questions.length - 1 || !answer) setDone(true); else setStep(step + 1); };
  const reset = () => { setSelected(null); setStep(0); setDone(false); };
  return <><PageHeader eyebrow="Diagnostic workflow" title={done ? "Possible fault detected" : selected === null ? "What are you troubleshooting?" : problems[selected].name} text={done ? "Based on your answers, this is the most likely cause and the safest way to verify it." : selected === null ? "Choose the symptom that best matches your circuit to begin a guided check." : "Answer each check from what you can observe on the bench."}/>
    {selected === null ? <div className="grid gap-4 pb-14 sm:grid-cols-2 lg:grid-cols-3">{problems.map((p,i) => <button key={p.name} onClick={() => setSelected(i)} className="frost group rounded-xl p-5 text-left ring-1 ring-border transition hover:-translate-y-1 hover:ring-primary/60"><div className="grid size-11 place-items-center rounded-lg bg-primary/10 text-signal ring-1 ring-primary/30"><p.icon className="size-5"/></div><h2 className="mt-4 font-semibold">{p.name}</h2><p className="mt-1 text-sm text-steel">{p.symptom}</p></button>)}</div>
    : done ? <Result selected={selected} reset={reset}/>
    : <section className="mx-auto max-w-3xl pb-16"><button onClick={reset} className="mb-4 inline-flex items-center gap-2 text-sm text-steel hover:text-foreground"><ArrowLeft className="size-4"/> Change problem</button><div className="frost rounded-xl p-6 ring-1 ring-border sm:p-8"><div className="flex items-center justify-between font-mono text-[10px] uppercase text-steel"><span>Step {step + 1} of {questions.length}</span><span className="text-signal">Checking signal path</span></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-primary transition-all" style={{width:`${((step+1)/questions.length)*100}%`}}/></div><h2 className="mt-8 text-balance text-2xl font-semibold">{questions[step]}</h2><p className="mt-3 text-sm leading-6 text-steel">Inspect the powered-off circuit first. Use a multimeter only where safe and appropriate.</p><div className="mt-8 grid grid-cols-2 gap-3"><Button variant="signal" size="xl" onClick={() => choose(true)}><Check/> Yes</Button><Button variant="console" size="xl" onClick={() => choose(false)}><AlertTriangle/> No</Button></div></div></section>}
  </>;
}

function Result({ selected, reset }: { selected: number; reset: () => void }) { return <section className="grid gap-5 pb-16 lg:grid-cols-[1fr_1.2fr]"><div className="frost rounded-xl p-6 ring-1 ring-border"><div className="font-mono text-[10px] uppercase text-amber">● Detected possible fault</div><h2 className="mt-3 text-2xl font-semibold">Open or incorrect connection</h2><p className="mt-3 text-sm leading-6 text-steel">The {problems[selected].name.toLowerCase()} symptoms point to a broken signal path, reversed polarity, or a loose connection near the load.</p></div><div className="frost rounded-xl p-6 ring-1 ring-border"><div className="font-mono text-[10px] uppercase text-signal">Recommended checks</div><ol className="mt-4 space-y-3">{["Disconnect power and inspect every connection against the schematic.", "Check continuity across wires, traces and solder joints.", "Verify polarity and pin numbering before reconnecting power.", "Power the circuit with current limiting and test the output again."].map((x,i)=><li key={x} className="flex gap-3 text-sm text-steel"><span className="grid size-6 shrink-0 place-items-center rounded-md bg-primary/10 font-mono text-[10px] text-signal">{i+1}</span><span className="pt-0.5">{x}</span></li>)}</ol><div className="mt-6 flex flex-wrap gap-3"><Button variant="console" onClick={reset}><RotateCcw/> Try Another Diagnosis</Button><Button variant="signal" onClick={() => alert("AI assistant is a demo in this prototype.")}><Bot/> Ask AI</Button></div></div></section>; }