import type { LucideIcon } from "lucide-react";

export function PageHeader({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <header className="pb-8 pt-10 sm:pt-14"><div className="font-mono text-[10px] uppercase text-signal">{eyebrow}</div><h1 className="mt-2 text-balance text-3xl font-bold sm:text-4xl">{title}</h1><p className="mt-3 max-w-2xl text-pretty leading-7 text-steel">{text}</p></header>; }

export function FeatureCard({ icon: Icon, title, text, status, tone }: { icon: LucideIcon; title: string; text: string; status: string; tone: "signal" | "amber" | "steel" }) {
  const toneClass = tone === "signal" ? "text-signal bg-primary/10 ring-primary/30" : tone === "amber" ? "text-amber bg-accent/10 ring-accent/30" : "text-steel bg-secondary ring-border";
  return <article className="frost rise rounded-xl p-5 ring-1 ring-border transition-transform hover:-translate-y-1"><div className={`grid size-11 place-items-center rounded-lg ring-1 ${toneClass}`}><Icon className="size-5"/></div><h2 className="mt-4 text-lg font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-steel">{text}</p><div className={`mt-4 font-mono text-[10px] uppercase ${tone === "amber" ? "text-amber" : tone === "signal" ? "text-signal" : "text-steel"}`}>● {status}</div></article>;
}

export function ScopePanel() { return <div className="frost rounded-xl p-4 ring-1 ring-border"><div className="flex justify-between font-mono text-[10px] uppercase"><span className="text-steel">Live channel</span><span className="text-signal">CH1 · 2V/div</span></div><div className="relative mt-3 h-44 overflow-hidden rounded-lg bg-ink ring-1 ring-border"><div className="circuit-grid absolute inset-0 opacity-60"/><svg className="absolute inset-0 h-full w-full text-signal" viewBox="0 0 500 180" fill="none" preserveAspectRatio="none" aria-label="Oscilloscope waveform"><path d="M0 95H78L88 82L99 110L112 35L126 145L140 92H220L230 70L242 118L254 50L268 132L280 95H360L370 82L382 110L394 35L408 145L420 92H500" stroke="currentColor" strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg><div className="sweep absolute inset-y-0 w-1/3 bg-gradient-to-r from-transparent via-primary/20 to-transparent"/></div><div className="mt-3 grid grid-cols-3 gap-2 font-mono text-[10px]"><Readout label="VCC" value="5.02V"/><Readout label="LOAD" value="180mA" amber/><Readout label="STATE" value="STABLE"/></div></div>; }
function Readout({label,value,amber}:{label:string;value:string;amber?:boolean}) { return <div className="rounded-md bg-secondary/70 px-2 py-2 ring-1 ring-border"><div className="text-steel">{label}</div><div className={amber ? "text-amber" : "text-signal"}>{value}</div></div>; }